modified PyLint minimum score

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -10,14 +10,29 @@ jobs:
         python-version: ["3.8", "3.9", "3.10"]
     steps:
     - uses: actions/checkout@v3
+
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pylint
+
     - name: Analysing the code with pylint
       run: |
         pylint $(git ls-files '*.py')
+
+    - name: Capture Pylint Score
+      id: pylint
+      run: |
+        pylint_score=$(pylint your_python_file.py --score=y)
+        echo "::set-output name=pylint_score::$pylint_score"
+
+    - name: Check Pylint Score
+      run: |
+        if [[ ${{ steps.pylint.outputs.pylint_score }} -lt 3 ]]; then
+          echo "Pylint score is below the minimum required score."
+          exit 1
